name: branch push resulting in PR creation

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: extract commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
